### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by s4vgR** [TheHive-Project/CortexDocs#20]
Hi,

I installed The Hive and Cortex using RPM. When i go to local web of both Hive and Cortex I get the same error:

My setup:
Linux lab.centos7 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
cortex.noarch  2.0.4-1
elasticsearch.noarch 6.3.2-1
thehive.noarch 3.0.10-1

```
2018-08-20 17:37:40,950 [INFO] from org.thp.cortex.services.ErrorHandler in application-akka.actor.default-dispatcher-5 - POST /api/maintenance/migrate returned 400
org.elasticsearch.transport.RemoteTransportException: [fQRBr16][127.0.0.1:9300][indices:admin/create]
Caused by: java.lang.IllegalArgumentException: Rejecting mapping update to [cortex_1] as the final mapping would have more than 1 type: [artifact, dblist, data, audit, analyzer, organization, report, job, user, analyzerConfig]
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:408)
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:356)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:280)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:443)
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:630)
        at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:267)
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:197)
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:132)
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:626)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
Looks like the mapping removal in ES 6+ disabled updating and with that any usage of Hive and Cortex. Any ideas? Thank you for help.

**Comment by nadouani** [comment]
Cortex doesn't support ES6. Thanks
