### ISSUE TITLE
Error Analizer VirusTotal - PIP3 StringIO

### ISSUE THREAD

**Issue by robben-ar** [TheHive-Project/CortexDocs#30]
When running an analysis with VirusTotal I returned the following error:

```
Invalid output
Traceback (most recent call last):
  File "VirusTotal/virustotal.py", line 7, in <module>
    from virustotal_api import PublicApi as VirusTotalPublicApi
  File "/opt/Cortex-Analyzers/analyzers/VirusTotal/virustotal_api.py", line 25, in <module>
    import StringIO
ImportError: No module named 'StringIO'
```

Apparently I have installed the cortexutils for python3

![image](https://user-images.githubusercontent.com/16881807/55289458-691d2780-539d-11e9-805a-62240533b08c.png)

Thank you,
Regards.-

**Comment by iwitz** [comment]
The VirusTotal analyzer was updated to be compatible with Python 3 and the file virustotal_api was deleted, this issue can be closed.
