### ISSUE TITLE
 UserMgmtCtrl control error

### ISSUE THREAD

**Issue by Haris1904** [TheHive-Project/CortexDocs#71]
Hi, I just recently installed cortex 3.0.1-1 but it seems to have issue updating the database, TheHive is working properly 
refer to the screenshot below as it keeps giving UserMgmtCtrl error
![Screenshot from 2020-10-23 07-23-55](https://user-images.githubusercontent.com/51179305/96998397-634be180-1501-11eb-8787-958a2ac1b343.png)

**Comment by aymansabri** [comment]
Hello, 

I have the same issue , when installed Cortex withe elasticsearch 7.x . 
@Haris1904  did you figure out how to resolve this ?

PS: Can you update the installation guide ; https://github.com/TheHive-Project/CortexDocs/blob/master/installation/install-guide.md#elasticsearch-installation  , the version of elasticsearch in the guide is 5.x, i'm soo confused about which version i should run.

Thanks

**Comment by 8ear** [comment]
Hi,
if you want i can share you my dockerfile and docker-compose file which works out of box.

**Comment by Haris1904** [comment]
Hi,
Yes please, it would be greatly appreciated
Regards

________________________________

**Comment by 8ear** [comment]
Hi,
I created my own repo with my own docker-compose and own cortex container.
https://github.com/it-bgk/cdc-plattform/
Check it out.

**Comment by halimB8** [comment]
Hello, 
I have the same issue with elasticsearch 7.10
did you find a solution for this error please ? 

Thanks for your help

**Comment by D4rkw0lv3s** [comment]
> Hello,
> I have the same issue with elasticsearch 7.10
> did you find a solution for this error please ?
> 
> It Elasticsearch logs I am getting these errors:
> 
> ```
> [2020-12-09T11:10:55,585][INFO ][o.e.c.m.MetadataCreateIndexService] [MASTER] failed on parsing mappings on index creation [cortex_4]
> org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [doc : {numeric_detection=false, date_detection=false, properties={data={type=binary}, sequenceCounter={type=long}, endDate={format=epoch_millis||basic_date_time_no_millis, type=date}, dataTypeList={type=keyword}, type={type=keyword}, objectType={type=keyword}, createdAt={format=epoch_millis||basic_date_time_no_millis, type=date}, cacheTag={type=keyword}, password={type=keyword}, details={type=nested, properties={updatedBy={type=keyword}, endDate={format=epoch_millis||basic_date_time_no_millis, type=date}, roles={type=keyword}, rateUnit={type=keyword}, errorMessage={fielddata=true, type=text}, description={fielddata=true, type=text}, dataTypeList={type=keyword}, label={type=keyword}, message={fielddata=true, type=text}, jobCache={type=long}, input={type=binary}, jobTimeout={type=long}, rate={type=long}, organization={type=keyword}, name={type=keyword}, tlp={type=long}, _id={type=keyword}, parameters={type=binary}, pap={type=long}, startDate={format=epoch_millis||basic_date_time_no_millis, type=date}, updatedAt={format=epoch_millis||basic_date_time_no_millis, type=date}, status={type=keyword}}}, pap={type=long}, updatedAt={format=epoch_millis||basic_date_time_no_millis, type=date}, dblist={type=keyword}, workerId={type=keyword}, updatedBy={type=keyword}, author={fielddata=true, type=text}, dataType={type=keyword}, rateUnit={type=keyword}, version={type=keyword}, tags={type=keyword}, license={fielddata=true, type=text}, input={type=binary}, binary={type=binary}, name={type=keyword}, workerDefinitionId={type=keyword}, workerName={type=keyword}, parameters={type=binary}, startDate={format=epoch_millis||basic_date_time_no_millis, type=date}, full={type=binary}, status={type=keyword}, dockerImage={fielddata=true, type=text}, fromCache={type=boolean}, rootId={type=keyword}, configuration={type=binary}, otherDetails={fielddata=true, type=text}, roles={type=keyword}, description={fielddata=true, type=text}, login={type=keyword}, operations={type=binary}, attachment={type=nested, properties={size={type=long}, name={type=keyword}, hashes={type=keyword}, id={type=keyword}, contentType={type=keyword}}}, jobTimeout={type=long}, rate={type=long}, requestId={type=keyword}, value={type=keyword}, key={type=keyword}, objectId={type=keyword}, baseConfig={type=keyword}, summary={type=binary}, preferences={type=binary}, errorMessage={fielddata=true, type=text}, avatar={type=binary}, label={type=keyword}, message={fielddata=true, type=text}, jobCache={type=long}, command={fielddata=true, type=text}, url={fielddata=true, type=text}, createdBy={type=keyword}, organization={type=keyword}, tlp={type=long}, relations={type=join, relations={dblist=[], sequence=[], data=[], audit=[], organization=[workerConfig, worker], report=[artifact], job=[report], user=[]}}, config={type=binary}, operation={type=keyword}, base={type=boolean}}}]
> 	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:417) ~[elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:353) ~[elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.updateIndexMappingsAndBuildSortOrder(MetadataCreateIndexService.java:977) ~[elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.lambda$applyCreateIndexWithTemporaryService$3(MetadataCreateIndexService.java:409) [elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:619) [elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexWithTemporaryService(MetadataCreateIndexService.java:407) [elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequestWithV1Templates(MetadataCreateIndexService.java:494) [elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:370) [elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:377) [elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:300) [elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47) [elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:702) [elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:324) [elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:219) [elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:73) [elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151) [elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678) [elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-7.10.0.jar:7.10.0]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
> 	at java.lang.Thread.run(Thread.java:832) [?:?]
> Caused by: org.elasticsearch.index.mapper.MapperParsingException: Root mapping definition has unsupported parameters:  [doc : {numeric_detection=false, date_detection=false, properties={data={type=binary}, sequenceCounter={type=long}, endDate={format=epoch_millis||basic_date_time_no_millis, type=date}, dataTypeList={type=keyword}, type={type=keyword}, objectType={type=keyword}, createdAt={format=epoch_millis||basic_date_time_no_millis, type=date}, cacheTag={type=keyword}, password={type=keyword}, details={type=nested, properties={updatedBy={type=keyword}, endDate={format=epoch_millis||basic_date_time_no_millis, type=date}, roles={type=keyword}, rateUnit={type=keyword}, errorMessage={fielddata=true, type=text}, description={fielddata=true, type=text}, dataTypeList={type=keyword}, label={type=keyword}, message={fielddata=true, type=text}, jobCache={type=long}, input={type=binary}, jobTimeout={type=long}, rate={type=long}, organization={type=keyword}, name={type=keyword}, tlp={type=long}, _id={type=keyword}, parameters={type=binary}, pap={type=long}, startDate={format=epoch_millis||basic_date_time_no_millis, type=date}, updatedAt={format=epoch_millis||basic_date_time_no_millis, type=date}, status={type=keyword}}}, pap={type=long}, updatedAt={format=epoch_millis||basic_date_time_no_millis, type=date}, dblist={type=keyword}, workerId={type=keyword}, updatedBy={type=keyword}, author={fielddata=true, type=text}, dataType={type=keyword}, rateUnit={type=keyword}, version={type=keyword}, tags={type=keyword}, license={fielddata=true, type=text}, input={type=binary}, binary={type=binary}, name={type=keyword}, workerDefinitionId={type=keyword}, workerName={type=keyword}, parameters={type=binary}, startDate={format=epoch_millis||basic_date_time_no_millis, type=date}, full={type=binary}, status={type=keyword}, dockerImage={fielddata=true, type=text}, fromCache={type=boolean}, rootId={type=keyword}, configuration={type=binary}, otherDetails={fielddata=true, type=text}, roles={type=keyword}, description={fielddata=true, type=text}, login={type=keyword}, operations={type=binary}, attachment={type=nested, properties={size={type=long}, name={type=keyword}, hashes={type=keyword}, id={type=keyword}, contentType={type=keyword}}}, jobTimeout={type=long}, rate={type=long}, requestId={type=keyword}, value={type=keyword}, key={type=keyword}, objectId={type=keyword}, baseConfig={type=keyword}, summary={type=binary}, preferences={type=binary}, errorMessage={fielddata=true, type=text}, avatar={type=binary}, label={type=keyword}, message={fielddata=true, type=text}, jobCache={type=long}, command={fielddata=true, type=text}, url={fielddata=true, type=text}, createdBy={type=keyword}, organization={type=keyword}, tlp={type=long}, relations={type=join, relations={dblist=[], sequence=[], data=[], audit=[], organization=[workerConfig, worker], report=[artifact], job=[report], user=[]}}, config={type=binary}, operation={type=keyword}, base={type=boolean}}}]
> 	at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:158) ~[elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:146) ~[elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:98) ~[elasticsearch-7.10.0.jar:7.10.0]
> 	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:415) ~[elasticsearch-7.10.0.jar:7.10.0]
> 	... 23 more
> ```
> 
> Thanks for your help

I'm using elasticsearch 7.10 and it's working fine with the cortex 3.1.0-1.

Docker image: 'thehiveproject/cortex:3.1.0-1'.

You can find some Official Docker Templates here: https://github.com/TheHive-Project/Docker-Templates

The new index will be cortex_5, but if you already had the cortex_4 (cortex 3.0.X), on the web interface it will prompt you to update the database, just click it and it's done, you have now the new version. See More here: https://github.com/TheHive-Project/CortexDocs/blob/master/admin/updating.md
